### PR TITLE
Convert packaged jars to OSGi bundles

### PR DESCRIPTION
**Pull request by CMoH**
Use maven-bundle-plugin to add appropriate OSGi headers to jars, thus
turning them into OSGi bundles.

I would also ask you kindly to deploy a release (3.2.0 ?) on maven central with these OSGi bundle headers, which would make integration into such projects easier for everyone.

Thank you

### CODE REVIEW

**Comment by JeffreyFalgout** [comment]
I'm pretty unfamiliar with OSGi and OSGi-Maven best practices. Are there any downsides to this change? 

- Would this prevent someone who's not using OSGi from using the produced jars?
- Is it possible to produce a normal jar and an OSGi jar so that someone who's not using OSGi doesn't have to worry about any extra bloat?

**Comment by CMoH** [comment]
OSGi bundles are basically jars with some extra manifest headers. These headers contain dependency information which helps OSGi containers manage multiple versions of the same jar within the same JVM.

I don't think such precautions for producing both jars are necessary. For instance, the `jsr305-3.0.1.jar` used as dependency by your project does have OSGi headers. So do many pervasive libraries (e.g. guava)

I also suggested a minor version increase (from 3.1 to 3.2) to account for OSGi semantic versioning, but also to suggest to humans that these headers appeared in the 3.2.x series. 

To detail this even further: code importing code from this bundle will use by default a range of `[3.2,4)` (meaning any version including 3.2 onwards until, but excluding version 4). Releasing headers in version 3.1.2 will lead to an automatic range `[3.1,4)`, which includes non-OSGI versions 3.1.0 and 3.1.1. It's not that you cannot specify 3.1.2 manually, it's just that most people won't realize they have to.

**Comment by JeffFaer** [comment]
I just released v3.2.0. It should be available in Maven central shortly.

**Comment by CMoH** [comment]
Thank you. I just bumped to this release and all works fine.

**Pull request merged**
